### PR TITLE
elephant and ampersand updates

### PR DESCRIPTION
**Pull request by Alextopher**
Bringing this back into PR land for some edits.

### CODE REVIEW

**Comment by Alextopher** [comment]
@CrazyHuman1 when you're ready click the "Ready for review" button :smile:

**Comment by Alextopher** [comment]
For tracking purposes this is to redo #9

**Comment by CrazyHuman1** [comment]
i know it has spelling errors but i have no way of fixing them because of being unable to open this branch in vscode and as a result i can't even add any of the new information that the pages that i have edited for this to be able to be added

**Review by CrazyHuman1 — COMMENTED** [review]
added spelling correction and ip address usage

**Comment by Alextopher** [comment]
> added spelling correction and ip address usage

Doesn't seem like you pushed any code :sweat_smile: You need run `git push` on your local machine. Make sure you don't Merge until @sophiacarlone has a chance to look over your final changes

**Comment by CrazyHuman1** [comment]
I don't see a ready to review button, but it should have been ready a while ago.

**Review by emberian — APPROVED** [review]

**Pull request merged**
